# Generated by Django 3.0.8 on 2020-08-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Craigslist_WebScraping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
